fix FreeENS.sol comments
the first 32 bytes of a bytes variable is its length (instead of `address`)

avoid using msize() to make optimizer happy.

> SyntaxError: The msize instruction cannot be used when the Yul optimizer is activated because it can change its semantics. Either disable the Yul optimizer or do not use the instruction.